[project]
  name            = "sqlalchemy-pgtrigger"
  version         = "0.0.0"
  description     = "sqlalchemy rewrite of django-pgtrigger"
  readme          = "readme.md"
  requires-python = ">=3.14"
  license         = "BSD-3-Clause"
  license-files   = ["license.md"]

  authors = [
    { name = "Joaquín Zúñiga", email = "jp.zuniga.dev@gmail.com" },
  ]

  classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.14",
  ]

  dependencies = [
    "sqlalchemy[asyncio,postgresql-psycopgbinary]>=2.0.52",
  ]

  [project.urls]
    Homepage = "https://github.com/jp-zuniga/sqlalchemy-pgtrigger"
    Issues   = "https://github.com/jp-zuniga/sqlalchemy-pgtrigger/issues"

  [project.optional-dependencies]
    alembic = ["alembic>=1.19.1"]

[dependency-groups]
  dev = [
    "alembic>=1.19.1",
    "hypothesis>=6.165.10",
    "mkdocstrings-python>=2.0.7",
    "prek>=0.4.14",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.4",
    "tombi>=1.4.1",
    "ty>=0.0.73",
    "zensical>=0.0.57",
  ]

[build-system]
  requires = [
    "uv_build>=0.11.20,<0.13.0",
  ]

  build-backend = "uv_build"

[tool.uv.build-backend]
  module-name   = "pgtrigger"
  module-root   = ""
  wheel-exclude = [".github", "docs", "tests"]
